### PR TITLE
feat: add k8s cloudbuild

### PR DESCRIPTION
**Pull request by vedantthapa**
Add cloudbuild configuration to run kubernetes schema validation. This build will only be triggered on changes to `kubernetes/**`.

I'll add a step to check for compliance using kyverno in a subsequent PR.

### CODE REVIEW

**Comment by vedantthapa** [comment]
@Stephen-ONeil Do you think it'd be helpful to organize all our cloudbuild configurations in a top level directory called `cloudbuild`?

**Comment by Stephen-ONeil** [comment]
> @Stephen-ONeil Do you think it'd be helpful to organize all our cloudbuild configurations in a top level directory called `cloudbuild`?

Hm, I've got a slight leaning towards keeping them in their respective sub-dirs. Local changes to, e.g., script names within a sub project would need to be mirrored in the respective cloudbuild, which tends to be a reason for keeping things near by, organizationally, in my mind. Think you can put your perspective in words so we can compare opinions?

**Review by Stephen-ONeil — APPROVED** [review]
:+1:

**Comment by vedantthapa** [comment]
> Hm, I've got a slight leaning towards keeping them in their respective sub-dirs. Local changes to, e.g., script names within a sub project would need to be mirrored in the respective cloudbuild, which tends to be a reason for keeping things near by, organizationally, in my mind. Think you can put your perspective in words so we can compare opinions?

I think your suggestion makes more sense.

My main argument was purely based on the ease of browsing through a repository's contents. If someone's only interested in looking at our cloud build configuration, then they could just navigate to the top-level `cloudbuild` directory. I've been that "someone" for the past few weeks, trying to browse repositories to get ideas on implementing tests in CI for kubernetes lol, so you can probably guess why I was leaning towards this approach lol. I've got to stop being so attached to github actions haha.

**Pull request merged**
