### PR TITLE
feat: add renovate config

### PR DESCRIPTION
**Pull request by vedantthapa**
Add renovate config from https://github.com/vedantthapa/k8s-devsecops/blob/main/.github/renovate.json5.

I'll install the github app on this repository once we merge this in.

### CODE REVIEW

**Review by Stephen-ONeil — APPROVED** [review]
Nice, approved :+1: 

I see the GitHub app is "provided complimentary of Mend", any sense that they might pull a paid-tier bait-and-switch? Guess we could also consider the chance that we could some day have to move off GitHub/have out ability to install arbitrary GitHub apps restricted. Seems self-hosting renovate is an option, but that achieving equivalent GitHub integration to the app would be a pain, right?

**Comment by vedantthapa** [comment]
Hmm, that's a fair point. The mend renovate app offers [these benefits](https://docs.renovatebot.com/modules/platform/github/#easiest-way-to-run-renovate), however, there are great docs if we want to self-host it. We'd have to pick an approach though, we can run in inside github actions ([CDS does this](https://github.com/cds-snc/renovate-app/blob/main/.github/workflows/renovate-app.yml)) or as a [kubernetes cron job](https://github.com/renovatebot/renovate/blob/main/docs/usage/examples/self-hosting.md#kubernetes). Both of those require us to manage secrets, so I'd be in favour of kubernetes cause secrets in github actions are already an issue for us.

**Comment by Stephen-ONeil** [comment]
> Thoughts?

Kubernetes cron job sounds good to me, keeps up with our gold-standard of cloud native/platform agnostic. Doesn't have to be a priority though, happy to see this turned on via the GitHub app and switching to in-cluster as a follow up issue.

**Comment by vedantthapa** [comment]
yeah! I'll add an issue for switching to a kubernetes cron job. Thanks!

**Pull request merged**
