### PR TITLE
feat: ignore pinning for flux managed images

### PR DESCRIPTION
**Pull request by vedantthapa**
As discussed in https://github.com/PHACDataHub/safe-inputs/pull/187#pullrequestreview-2148292813.

### CODE REVIEW

**Review by Stephen-ONeil — CHANGES_REQUESTED** [review]
Renovate doesn't seem happy, but I don't have a details button on this failure to see why. Is this an access thing, can you view the details?
image

**Comment by vedantthapa** [comment]
I tried a couple of changes but it still won't work. What's weird to me is that a local validation of the config succeeds without any errors - 
```sh
> npx --yes --package renovate -- renovate-config-validator --strict
(node:65841) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 INFO: Validating renovate.json5
 INFO: Config validated successfully
```

Moreover, as [per the docs](https://docs.renovatebot.com/config-validation/#validate-your-config-automatically) renovate should add a comment on this PR with the validation error details.

**Comment by Stephen-ONeil** [comment]
Maybe the validation error details ALSO got rate limited :laughing:. Only half joking there.

**Comment by vedantthapa** [comment]
hahah totally possible!

I'm gonna trust the local config validator and merge this in. Worst case scenario, renovate creates an issue asking us to fix the config.

**Review by Stephen-ONeil — APPROVED** [review]
Approved, since merging is our best bet at figuring out what's wrong.

**Pull request merged**
